services:
  db:
    image: postgres:15
    container_name: DB
    restart: always
    volumes:
      - ~/.pg.pg_data/fox6:/var/lib/postgresql/data
    env_file:
      - .env

  fox6:
    build:
      context: .
    container_name: fox6
    image: fox6
    restart: always
    entrypoint: /fox6/start.sh
    depends_on:
      - db
    volumes:
      - static:/fox6/static
      - media:/fox6/media
    env_file:
      - .env
    environment:
      - VIRTUAL_HOST=${ALLOWED_HOST}
      - LETSENCRYPT_HOST=${ALLOWED_HOST}
      - DEFAULT_HOST=${ALLOWED_HOST}

  nginx:
    build:
      context: ./nginx/
    container_name: NGINX
    restart: always
    volumes:
      - static:/fox6/static
      - media:/fox6/media
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - fox6
    ports:
      - "80:80"
      - "443:443"

  acme_companion:
    image: nginxproxy/acme-companion
    container_name: ACME
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
      - certs:/etc/nginx/certs

volumes:
  static:
  media:
  certs:
  vhost:
  html:
  acme: